[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
sword = { git = "https://github.com/MrRevillod/sword.git", branch = "main", features = [
    "validation-validator",
] }

jsonwebtoken = { version = "10.2.0", features = ["rust_crypto"] }

uuid = { version = "1.19.0", features = ["serde", "v4"] }
chrono = { version = "0.4.42", features = ["serde"] }

serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
validator = { version = "0.20.0", features = ["derive"] }

sqlx = { version = "0.8.6", features = [
    "chrono",
    "macros",
    "postgres",
    "runtime-tokio",
    "uuid",
] }

tracing = "0.1.44"
tracing-subscriber = "0.3.22"
thiserror = "2.0.17"
simple-ldap = "8.0.1"
url = "2.5.0"
tokio = { version = "1.0", features = ["sync"] }
