[server]
port = 8000
host = "0.0.0.0"
body_limit = 5242880
request_timeout_secs = 15

[postgres-db]
uri = "${POSTGRES_DATABASE_URL:postgres://localhost:5432/code-analyzer-db}"
migrations_path = "migrations"
min_connections = 1
max_connections = 10
acquire_timeout_ms = 5000

[jsonwebtoken]
secret = "${JWT_SECRET}"

[cors]
allow_credentials = false
allowed_origins = ["http://localhost:3000", "http://localhost/"]
allowed_methods = ["GET", "POST", "PUT", "PATCH", "DELETE"]
allowed_headers = ["Content-Type", "Authorization"]
